### ISSUE TITLE
Arrow keys move selected square in an unintuitive way

### ISSUE THREAD

**Issue by Geemer** [Jarno458/Sudoku-for-Archipelago#3]
Using the arrow keys to move the selected square results in the square only moving up or down, only moving to the other end of the next column if the top or bottom has been reached.

![image](https://user-images.githubusercontent.com/6912397/206790109-662c259a-f6d8-44a5-bb5f-d19e228e6ad6.png)
In this screenshot I had just clicked the top middle square of the bottom middle grid and typed a 6. To get to the open square in the row I expected to have to press the right arrow twice, but this resulted in the square moving to the bottom square of the grid.

Needing to use the mouse to move around in a sudoku game is very unpleasant.

**Comment by Jarno458** [comment]
This is correct, I didnt really specify this behaviour, it's how windows let's you traverse a form

**Comment by Jarno458** [comment]
project is nolonger maintained
