### ISSUE TITLE
!hint behavior changed to !hint_location in 0.3.7 update

### ISSUE THREAD

**Issue by wertercatt** [Jarno458/Sudoku-for-Archipelago#7]
When Sudoku was updated to support Archipelago 0.3.7, the hint filter was changed from only giving hints for the connected slot's items, to only giving hints for items found in the connected slot. This behavior seems to drastically reduce the potential usability of Sudoku when the slot is actually in BK Mode, and can't get any new checks.
As the Commit message doesn't mention this, I'd like to know if this was an intentional change.
 https://github.com/Jarno458/Sudoku-for-Archipelago/commit/53a2c84b2b803a14e1f182c57c552711f80d36b0

**Comment by Jarno458** [comment]
project is nolonger maintained
